version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --aot -prod
    post_build:
        commands:
            - echo Build completed on `date`
            - chmod +x *.sh
            
artifacts:
    files:
        - ./appspec.yml
        - ./dist/**/*
